### ISSUE TITLE
Possibility to use same thread when a Thread already exists between two users

### ISSUE THREAD

**Issue by vamsiikrishna** [FriendsOfSymfony/FOSMessageBundle#259]
Hi,
instead of creating a new thread, I want to use the same thread between 2 users ( if it exists ). I am trying to find out if there are some methods in the entity manager to achieve this functionality .

Thanks

**Comment by tgalopin** [comment]
Hello!

The proper way to do this is to use the NewThreadFormHandler. You can define a custom handler based on the default one (`FormHandler/NewThreadMessageFormHandler.php`) and use it by editing the config:

``` yaml
fos_message:
    new_thread_form:
        handler: <your_service_name>
```

After this, the newThreadAction will call your handler in order to create a new thread, so you can technically do whatever you want here as it's a service.

If you need more help, don't hesitate, I'll explain more.

**Comment by tgalopin** [comment]
I close this, if you need more help, don't hesitate to ask :) .
