### ISSUE TITLE
One query for each message

### ISSUE THREAD

**Issue by Lyrikz** [FriendsOfSymfony/FOSMessageBundle#272]
Hello,

I'm making an instant tchat with FOSMessageBundle and Nodejs. Everythings is ok expect one thing. When I do $provider->getThread($id)->getMessages(); this execute one query for each message. I have something like 70 messages in my db, so 70 useless queries. I tried some solutions that I found on google, but nothing works for me...

The query is :
SELECT is_read
FROM MessageMetadata
WHERE message_id = ? (id parameter)

I dont even care about the is_read field, i'm not using it right now.

Does anyone have the same problem?
Sorry for bad english.

**Comment by pimolo** [comment]
:+1: if anyone has a solution...

**Comment by tgalopin** [comment]
That's a know issue with the current implementation. The best way to work around that for the moment is to use directly the repositories of your entities and create your own query. It will be fixed in the next version we are currently working on (check https://github.com/FriendsOfSymfony/FOSMessage to learn more :) ).

If you need more help, don't hesitate to ask. If you don't, please close to improve the tracker readability :) .

**Comment by Lyrikz** [comment]
Thanks you for your answer! I will close the issue. :)
