### ISSUE TITLE
similar library 

### ISSUE THREAD

**Issue by hero789** [FriendsOfSymfony/FOSMessageBundle#292]
hello , 
i've been use "FOSMessage" library for testing but i think the documentation and the library still in development as mentioned , so  can i easily  migrate to library "FOSMessageBundle" specially i'm using symfony actually i was confused about the difference between them .

**Comment by tgalopin** [comment]
The bundle is an "old" project, created before the library. It was meant to provide a useful basis for developers to create a user-to-user messaging system.

However, as the bundle lost its maintainers (I am now the maintainer), a discussion started to externalize the core concepts of the bundle in a framework-agnostic library. That's a current work in progress and that's why the library is not yet ready to use.

**Comment by hex333ham** [comment]
moving old library discussions to #332
