### ISSUE TITLE
Provider to return Query Builders?

### ISSUE THREAD

**Issue by kshishkin** [FriendsOfSymfony/FOSMessageBundle#294]
I can provide code via pull request if needed.

I'd like FOS\MessageBundle\Provider\Provider have methods to return query builders instead of selected data. The rationale is easier integration with paginators. 

What are your thoughts?

**Comment by tgalopin** [comment]
Hello @kshishkin,

The provider is only an easier to use tool to access the bundle data, but you can access the repositories managers directly in order to get query builders. For instance, you can access the ThreadManager (https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/EntityManager/ThreadManager.php) by injecting it in a custom service (using the service `fos_message.thread_manager`).

If you want to add methods in the Provider, you can also extends it and configure the configuration key `fos_message.provider` to use your own service instead.

I don't think query builders shoud be provided natively, but I may be wrong.

**Comment by kshishkin** [comment]
Hi @tgalopin, 

I have options you mentioned in place, I've overloaded both provider & manager services for my needs. 

I just thought combining FOSMessageBundle with paginators must by such a common scenario that query builders would fit very well in the provider, especially that the performance impact has to be significant. 

I imagine in medium size application messaging component would be significant share of it's data. Juggling it without paginators - or with paginators based on referenced full entity collections might hit app performance. Also, query builders as promoted solution give options like sorting & filtering at ease.

Having that said, I'm completely fine with leaving it as is, beautifully designed for ease of overriding. I just think this change might be useful for other newcomers.

Thanks for your consideration

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
